# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57221e5abd6345edd8698ec355001938a87ffd506ea353688e49b9aee6146beb618e2a99ca24493dac49f35bacf4af31b3bf9821fac54c4c99abf3d743275b02

test:
  secret_key_base: e37a19e19565308f40b3e73c72431c5fbb4eae92b18dc034539e68fe59c1ee3439c4a300cd4e2ccbeb1deb9c78b4f3204f35b9c010ffe51ffe09c09ac32c56ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
